### ISSUE TITLE
Capo is always set to None

### ISSUE THREAD

**Issue by ozls** [More-Than-Solitaire/Tabs-Lite#70] opened 2022-08-18 07:36 UTC
I just installed the application, and it seems to be exactly something I have been praying for, so a big thank you first and foremost. Second, I have this small issue that I don't think would be hard to fix: all tabs have "Capo: None" in their header. This is the case even for tabs I know for a fact need a capo, for instance Wonderwall (see screenshot; capo should be in 2). Thank you in advance for your attention! 
![Screenshot_20220818-093102](https://user-images.githubusercontent.com/34961309/185337166-c0f78da4-ac38-4afa-a934-00f9742887b9.png)
!

**Comment by cullub** [comment] 2022-12-04 17:07
Hi there, sorry for the delay!  Good catch!  I'll have to look into that in more detail to figure out what the issue is.  Note that even for some songs that might need a capo, if the tab author forgot to list that in the metadata the tab will still show as needing no capo.  I don't think that's the issue here, since I looked around quickly and couldn't find any songs that showed a non-zero capo in the app.  I'll update here when I know more.

**Comment by cullub** [comment] 2023-12-18 15:32
This issue seems to still be around; reopening for more research

**Comment by cullub** [comment] 2024-02-01 12:03
This is fixed in the latest update. For any tab that is already saved locally to your phone, just reload that tab (three dot menu then Reload).

**Closed** 2024-02-01 12:04 UTC
Labels: bug
